framework:
    default_locale: es
    translator:
        default_path: '%kernel.project_dir%/translations'
        paths:
            - '%kernel.project_dir%/translations/test'
        fallbacks:
            - es
