products:
  salud:
    name: 'salud'
    steps: 3
    children:
      familia:
        name: 'familia'
        children:
          individual:
            name: 'individual'
            path: 'individual'
          familiar:
            name: 'familiar'
            path: 'familiar'
          mayores:
            name: 'mayores'
            path: 'mayores'
          embarazada:
            name: 'embarazada'
            path: 'embarazada'
      negocio:
        name: 'negocio'
        children:
          autonomo:
            name: 'autonomo'
            path: 'autonomo'
          menos5:
            name: 'menos5'
            path: 'menos5'
          mas5:
            name: 'mas5'
            path: 'mas5'
          mas100:
            name: 'mas100'
            path: 'mas100'
  dental:
    name: 'dental'
    steps: 2
    children:
      cobdental:
        name: 'cobdental'
        path: 'cobdental'
        children:
      dentalysalud:
        name: 'dentalysalud'
        path: 'dentalysalud'
        children:
  mascotas:
    name: 'mascotas'
    steps: 2
    children:
      mascotas:
        name: 'mascotas'
        path: 'mascotas'
        children:
  decesos:
    name: 'decesos'
    steps: 2
    children:
      decesos:
        name: 'decesos'
        path: 'decesos'
        children: