index:
   path: /
   controller: App\Controller\IndexController::index
product:
   path: /product
   controller: App\Controller\ProductController::index
test:
   path: /test
   controller: App\Controller\TestController::index