<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSus8TU8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSus8TU8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSus8TU8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSus8TU8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSus8TU8\App_KernelDevDebugContainer([
    'container.build_hash' => 'Sus8TU8',
    'container.build_id' => '598f65f7',
    'container.build_time' => 1586355923,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSus8TU8');
