<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFcG5qeu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFcG5qeu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFcG5qeu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFcG5qeu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFcG5qeu\App_KernelDevDebugContainer([
    'container.build_hash' => 'FcG5qeu',
    'container.build_id' => '23cdfcc3',
    'container.build_time' => 1586342970,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFcG5qeu');
