<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'bysidecar' => [
            'js' => [
                '/build/runtime.js',
                '/build/vendors~bysidecar.js',
                '/build/bysidecar.js',
            ],
        ],
    ],
],

]];
